plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1' //um Fat-Jar mit allen Dependendies zu erzeugen
}

group = 'de.bund.zrb.proxy'

// Version kommt idealerweise aus gradle.properties (siehe unten)
if (!project.hasProperty('version')) {
    version = '0.0.1-SNAPSHOT'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'com.google.code.gson:gson:2.10.1'
    
    // Windows Proxy Resolver Library (WPAD/PAC support ohne PowerShell)
    implementation 'com.aresstack:win-proxy-java:0.1.0-beta.1'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(
                'Main-Class': 'de.bund.zrb.app.ProxyControlFrame'
        )
    }
}

shadowJar {
    archiveClassifier.set('all')
    manifest {
        attributes(
                'Main-Class': 'de.bund.zrb.app.ProxyControlFrame'
        )
    }
}